[package]
name = "ComputerGraphics"
version = "0.1.0"
authors = ["Jake Moss <jake.moss@uqconnect.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
